name: Deploy to self-hosted runners

on:
  workflow_run:
    workflows:
      - Build and Push Docker Images
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')

    strategy:
      fail-fast: false
      matrix:
        target:
          - name: b01
            runner: [self-hosted, production, b01, apiservices]
            profile: kickfriends-prod

          #- name: worker01
          #  runner: [self-hosted, production, worker01, apiservices]
          #  profile: worker01

          #- name: frontend01
          #  runner: [self-hosted, production, frontend01, apiservices]
          #  profile: frontend01

    runs-on: ${{ matrix.target.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Deploy profile
        run: |
          docker compose --env-file /home/theuser/__dotenv__/env.apiservices --profile "${{ matrix.target.profile }}" pull
          docker compose --env-file /home/theuser/__dotenv__/env.apiservices --profile "${{ matrix.target.profile }}" up -d
          docker image prune -f